[project]
name = "review-classifier-tester"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "elizarcarsleep", email = "elizar.konovalov@carsleep.io" }
]
requires-python = ">=3.13"
dependencies = [
    "datasets>=5.0.1",
    "scikit-learn>=1.9.1",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]

[project.scripts]
review-classifier-tester = "review_classifier_tester:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
